### PR TITLE
Create Chinses Translation

### PR DESCRIPTION
**Pull request by Hotaru-Snowy**

### CODE REVIEW

**Comment by Rad586** [comment]
[新建文本文档.txt](https://github.com/ArcanePigeon/ProbablyChests/files/10020023/default.txt)
这是我个人版本的汉化，如果觉得有的地方翻得还可以，请考虑采纳？

**Comment by Rivmun** [comment]
我也建议把“模仿者”改成“宝箱怪”，毕竟中文语境里“模仿者”并没有很清晰的指代，而且纵观游戏汉化，基本都会把“mimic”翻译成宝箱怪。
另外建议把模组汉化名称改为“奇遇宝箱”，会较“应该是”更雅致一些。

**Comment by Hotaru-Snowy** [comment]
@Rad233 @Rivmun I am sorry for I didnt notice your reply. And I am not good for translation. When I play this mod and find it dont have Chinese text, I translated it clumsy and create a pull request to try to help other people.
Im glad that someone can provide a better translation and believe the author is also willing to accept it. If you have better translation, you can create a pull request according to the format. It might be better than upload a file as an appendix.

**Comment by Rivmun** [comment]
@Hotaru-Snowy ”宝箱怪“我觉得其实算小问题，主要我看见你把”probably chests“翻译成了”应该是“有点难蚌。这个名字真的应该商榷一下。
主要是懒得建分支拉PR，怪麻烦的 :P

**Pull request merged**
